# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1055, 635)
        MainWindow.setMaximumSize(QtCore.QSize(1500, 16777215))
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.widget = QtGui.QWidget(self.centralWidget)
        self.widget.setEnabled(True)
        self.widget.setGeometry(QtCore.QRect(0, 0, 336, 570))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(189, 189, 94))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 222, 124))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(94, 94, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 126, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(189, 189, 94))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 222, 174))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(189, 189, 94))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 222, 124))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(94, 94, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 126, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(189, 189, 94))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 222, 174))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(94, 94, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(189, 189, 94))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 222, 124))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(94, 94, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 126, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(94, 94, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(94, 94, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(189, 189, 94))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(189, 189, 94))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(189, 189, 94))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.widget.setPalette(palette)
        self.widget.setAutoFillBackground(True)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.widget)
        self.gridLayout_2.setMargin(11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.intCheckBox = QtGui.QCheckBox(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri Light"))
        font.setPointSize(10)
        self.intCheckBox.setFont(font)
        self.intCheckBox.setObjectName(_fromUtf8("intCheckBox"))
        self.gridLayout_2.addWidget(self.intCheckBox, 1, 7, 1, 1)
        self.chooseFunctionComboBox = QtGui.QComboBox(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri Light"))
        font.setPointSize(10)
        self.chooseFunctionComboBox.setFont(font)
        self.chooseFunctionComboBox.setObjectName(_fromUtf8("chooseFunctionComboBox"))
        self.chooseFunctionComboBox.addItem(_fromUtf8(""))
        self.chooseFunctionComboBox.addItem(_fromUtf8(""))
        self.chooseFunctionComboBox.addItem(_fromUtf8(""))
        self.chooseFunctionComboBox.addItem(_fromUtf8(""))
        self.chooseFunctionComboBox.addItem(_fromUtf8(""))
        self.chooseFunctionComboBox.addItem(_fromUtf8(""))
        self.chooseFunctionComboBox.addItem(_fromUtf8(""))
        self.chooseFunctionComboBox.addItem(_fromUtf8(""))
        self.chooseFunctionComboBox.addItem(_fromUtf8(""))
        self.chooseFunctionComboBox.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.chooseFunctionComboBox, 0, 3, 1, 5)
        self.mindoubleSpinBox = QtGui.QDoubleSpinBox(self.widget)
        self.mindoubleSpinBox.setMinimum(-4.0)
        self.mindoubleSpinBox.setMaximum(4.99)
        self.mindoubleSpinBox.setSingleStep(0.1)
        self.mindoubleSpinBox.setProperty("value", -3.0)
        self.mindoubleSpinBox.setObjectName(_fromUtf8("mindoubleSpinBox"))
        self.gridLayout_2.addWidget(self.mindoubleSpinBox, 1, 4, 1, 2)
        self.beforeCheckBox = QtGui.QCheckBox(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri Light"))
        font.setPointSize(10)
        self.beforeCheckBox.setFont(font)
        self.beforeCheckBox.setObjectName(_fromUtf8("beforeCheckBox"))
        self.gridLayout_2.addWidget(self.beforeCheckBox, 2, 7, 1, 1)
        self.generateButton = QtGui.QPushButton(self.widget)
        self.generateButton.setObjectName(_fromUtf8("generateButton"))
        self.gridLayout_2.addWidget(self.generateButton, 11, 6, 1, 2)
        self.chooseSearchToolBox = QtGui.QToolBox(self.widget)
        self.chooseSearchToolBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.chooseSearchToolBox.setObjectName(_fromUtf8("chooseSearchToolBox"))
        self.blindSearch = QtGui.QWidget()
        self.blindSearch.setGeometry(QtCore.QRect(0, 0, 318, 69))
        self.blindSearch.setObjectName(_fromUtf8("blindSearch"))
        self.chooseSearchToolBox.addItem(self.blindSearch, _fromUtf8(""))
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 318, 69))
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.chooseSearchToolBox.addItem(self.page_2, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.chooseSearchToolBox, 14, 0, 1, 8)
        self.chooseSearchLabel = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri Light"))
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.chooseSearchLabel.setFont(font)
        self.chooseSearchLabel.setObjectName(_fromUtf8("chooseSearchLabel"))
        self.gridLayout_2.addWidget(self.chooseSearchLabel, 12, 0, 1, 8)
        self.resultsLabel = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri Light"))
        font.setPointSize(12)
        self.resultsLabel.setFont(font)
        self.resultsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.resultsLabel.setObjectName(_fromUtf8("resultsLabel"))
        self.gridLayout_2.addWidget(self.resultsLabel, 15, 0, 1, 2)
        self.resultTextEdit = QtGui.QTextEdit(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resultTextEdit.sizePolicy().hasHeightForWidth())
        self.resultTextEdit.setSizePolicy(sizePolicy)
        self.resultTextEdit.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri Light"))
        font.setPointSize(10)
        self.resultTextEdit.setFont(font)
        self.resultTextEdit.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.resultTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.resultTextEdit.setObjectName(_fromUtf8("resultTextEdit"))
        self.gridLayout_2.addWidget(self.resultTextEdit, 16, 0, 1, 8)
        self.frequentionLabel = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri Light"))
        font.setPointSize(10)
        self.frequentionLabel.setFont(font)
        self.frequentionLabel.setObjectName(_fromUtf8("frequentionLabel"))
        self.gridLayout_2.addWidget(self.frequentionLabel, 4, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 15, 5, 1, 1)
        self.changeButton = QtGui.QPushButton(self.widget)
        self.changeButton.setObjectName(_fromUtf8("changeButton"))
        self.gridLayout_2.addWidget(self.changeButton, 4, 7, 1, 1)
        self.maxdoubleSpinBox = QtGui.QDoubleSpinBox(self.widget)
        self.maxdoubleSpinBox.setMinimum(-4.0)
        self.maxdoubleSpinBox.setMaximum(4.99)
        self.maxdoubleSpinBox.setSingleStep(0.1)
        self.maxdoubleSpinBox.setProperty("value", 3.0)
        self.maxdoubleSpinBox.setObjectName(_fromUtf8("maxdoubleSpinBox"))
        self.gridLayout_2.addWidget(self.maxdoubleSpinBox, 2, 4, 1, 2)
        self.frequentionDoubleSpinBox = QtGui.QDoubleSpinBox(self.widget)
        self.frequentionDoubleSpinBox.setMinimum(0.0)
        self.frequentionDoubleSpinBox.setMaximum(2.99)
        self.frequentionDoubleSpinBox.setSingleStep(0.01)
        self.frequentionDoubleSpinBox.setProperty("value", 0.2)
        self.frequentionDoubleSpinBox.setObjectName(_fromUtf8("frequentionDoubleSpinBox"))
        self.gridLayout_2.addWidget(self.frequentionDoubleSpinBox, 4, 3, 1, 3)
        self.pointsdoubleSpinBox = QtGui.QDoubleSpinBox(self.widget)
        self.pointsdoubleSpinBox.setMinimum(0.0)
        self.pointsdoubleSpinBox.setMaximum(2.99)
        self.pointsdoubleSpinBox.setSingleStep(0.01)
        self.pointsdoubleSpinBox.setProperty("value", 0.2)
        self.pointsdoubleSpinBox.setObjectName(_fromUtf8("pointsdoubleSpinBox"))
        self.gridLayout_2.addWidget(self.pointsdoubleSpinBox, 3, 4, 1, 2)
        self.numOfSpecimen = QtGui.QLabel(self.widget)
        self.numOfSpecimen.setObjectName(_fromUtf8("numOfSpecimen"))
        self.gridLayout_2.addWidget(self.numOfSpecimen, 11, 0, 1, 1)
        self.numOfSpecimenSpinBox = QtGui.QSpinBox(self.widget)
        self.numOfSpecimenSpinBox.setObjectName(_fromUtf8("numOfSpecimenSpinBox"))
        self.gridLayout_2.addWidget(self.numOfSpecimenSpinBox, 11, 3, 1, 3)
        self.chooseFunctionLabel = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri Light"))
        font.setPointSize(10)
        self.chooseFunctionLabel.setFont(font)
        self.chooseFunctionLabel.setObjectName(_fromUtf8("chooseFunctionLabel"))
        self.gridLayout_2.addWidget(self.chooseFunctionLabel, 0, 0, 1, 3)
        self.pointsLabel = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri Light"))
        font.setPointSize(10)
        self.pointsLabel.setFont(font)
        self.pointsLabel.setObjectName(_fromUtf8("pointsLabel"))
        self.gridLayout_2.addWidget(self.pointsLabel, 3, 0, 1, 1)
        self.maxNumberLabel = QtGui.QLabel(self.widget)
        self.maxNumberLabel.setObjectName(_fromUtf8("maxNumberLabel"))
        self.gridLayout_2.addWidget(self.maxNumberLabel, 2, 1, 1, 3)
        self.minNumberLabel = QtGui.QLabel(self.widget)
        self.minNumberLabel.setObjectName(_fromUtf8("minNumberLabel"))
        self.gridLayout_2.addWidget(self.minNumberLabel, 1, 1, 1, 3)
        self.minLabel = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri Light"))
        font.setPointSize(10)
        self.minLabel.setFont(font)
        self.minLabel.setObjectName(_fromUtf8("minLabel"))
        self.gridLayout_2.addWidget(self.minLabel, 1, 0, 1, 1)
        self.maxLabel = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri Light"))
        font.setPointSize(10)
        self.maxLabel.setFont(font)
        self.maxLabel.setObjectName(_fromUtf8("maxLabel"))
        self.gridLayout_2.addWidget(self.maxLabel, 2, 0, 1, 1)
        self.line = QtGui.QFrame(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setMinimumSize(QtCore.QSize(0, 4))
        self.line.setSizeIncrement(QtCore.QSize(0, 0))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_2.addWidget(self.line, 9, 0, 2, 8)
        self.pointsNumberLabel = QtGui.QLabel(self.widget)
        self.pointsNumberLabel.setObjectName(_fromUtf8("pointsNumberLabel"))
        self.gridLayout_2.addWidget(self.pointsNumberLabel, 3, 1, 1, 3)
        self.visualisationWidget = QtGui.QWidget(self.centralWidget)
        self.visualisationWidget.setGeometry(QtCore.QRect(359, 0, 661, 570))
        self.visualisationWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 106, 53))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 222, 124))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(94, 94, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 126, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(189, 189, 94))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 222, 174))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 106, 53))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 222, 124))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(94, 94, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 126, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(189, 189, 94))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 222, 174))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(94, 94, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 106, 53))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 222, 124))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(94, 94, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 126, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(94, 94, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(94, 94, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(189, 189, 94))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(189, 189, 94))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(189, 189, 94))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.visualisationWidget.setPalette(palette)
        self.visualisationWidget.setAutoFillBackground(True)
        self.visualisationWidget.setObjectName(_fromUtf8("visualisationWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.visualisationWidget)
        self.verticalLayout.setMargin(11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.visualisationLabel = QtGui.QLabel(self.visualisationWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri Light"))
        font.setPointSize(14)
        self.visualisationLabel.setFont(font)
        self.visualisationLabel.setObjectName(_fromUtf8("visualisationLabel"))
        self.verticalLayout.addWidget(self.visualisationLabel)
        self.graphicsView = QtGui.QGraphicsView(self.visualisationWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setMinimumSize(QtCore.QSize(0, 503))
        self.graphicsView.setMaximumSize(QtCore.QSize(16777215, 1000))
        self.graphicsView.setBaseSize(QtCore.QSize(0, 0))
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.verticalLayout.addWidget(self.graphicsView)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1055, 21))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.chooseSearchToolBox.setCurrentIndex(0)
        QtCore.QObject.connect(self.maxdoubleSpinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(QString)")), self.maxNumberLabel.setText)
        QtCore.QObject.connect(self.mindoubleSpinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(QString)")), self.minNumberLabel.setText)
        QtCore.QObject.connect(self.pointsdoubleSpinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(QString)")), self.pointsNumberLabel.setText)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.intCheckBox.setText(_translate("MainWindow", "celočíselné", None))
        self.chooseFunctionComboBox.setItemText(0, _translate("MainWindow", "First De Jong", None))
        self.chooseFunctionComboBox.setItemText(1, _translate("MainWindow", "Rosenbrocks Saddle", None))
        self.chooseFunctionComboBox.setItemText(2, _translate("MainWindow", "Third De Jong", None))
        self.chooseFunctionComboBox.setItemText(3, _translate("MainWindow", "Forth De Jong", None))
        self.chooseFunctionComboBox.setItemText(4, _translate("MainWindow", "Rastrigin", None))
        self.chooseFunctionComboBox.setItemText(5, _translate("MainWindow", "Schewefel", None))
        self.chooseFunctionComboBox.setItemText(6, _translate("MainWindow", "Griewangkova", None))
        self.chooseFunctionComboBox.setItemText(7, _translate("MainWindow", "Sine Envelope", None))
        self.chooseFunctionComboBox.setItemText(8, _translate("MainWindow", "Sine Wave", None))
        self.chooseFunctionComboBox.setItemText(9, _translate("MainWindow", "Víceúčelová testovací funkce", None))
        self.beforeCheckBox.setText(_translate("MainWindow", "pred", None))
        self.generateButton.setText(_translate("MainWindow", "Generovat", None))
        self.chooseSearchToolBox.setItemText(self.chooseSearchToolBox.indexOf(self.blindSearch), _translate("MainWindow", "Náhodné prohledávání", None))
        self.chooseSearchLabel.setText(_translate("MainWindow", "VYBERTE VYHLEDÁVACÍ FUNKCI", None))
        self.resultsLabel.setText(_translate("MainWindow", "VÝSLEDKY", None))
        self.frequentionLabel.setText(_translate("MainWindow", "Frekvence:", None))
        self.changeButton.setText(_translate("MainWindow", "Změnit", None))
        self.numOfSpecimen.setText(_translate("MainWindow", "počet jedinců", None))
        self.chooseFunctionLabel.setText(_translate("MainWindow", "Vyberte funkci", None))
        self.pointsLabel.setText(_translate("MainWindow", "hustota bodů:", None))
        self.maxNumberLabel.setText(_translate("MainWindow", "3,00", None))
        self.minNumberLabel.setText(_translate("MainWindow", "-3,00", None))
        self.minLabel.setText(_translate("MainWindow", "minimum:", None))
        self.maxLabel.setText(_translate("MainWindow", "maximum:", None))
        self.pointsNumberLabel.setText(_translate("MainWindow", "0,2", None))
        self.visualisationLabel.setText(_translate("MainWindow", "Vizualizace", None))

